### ISSUE TITLE
Store state to be initialized on every open window (production issue only).

### ISSUE THREAD

**Issue by rossbulat** [polkadot-live/polkadot-live-app#2]
In production, local storage is blank on new windows. We may want to completely discontinue using local storage (it is currently used for storing fetched ledger and vault addresses) and rely on Electron Store solely, to keep one consistent data source.

- [x] Move local storage to Electron store and create ipc routes to manage?

**Comment by danebulat** [comment]
Addresses are now stored in Electron store and local storage is no longer used.
