### ISSUE TITLE
⏳ Add Settings window and initial settings

### ISSUE THREAD

**Issue by rossbulat** [polkadot-live/polkadot-live-app#21]
- [x] Add a new window for Settings. 
    - Make “native notifications toggle” an icon, and add notification toggle to Settings.
    - Add theme toggling to Settings.

- [x] Add a syncing animation for when events are being processed.

- [x] Add more information on connected networks.
    - RPC endpoint URL, or “connected to light client”.
    - Connected / disconnected

**Comment by danebulat** [comment]
Since opening this issue, the Settings window has  been implemented.
